DROP TABLE IF EXISTS project_skills CASCADE;
CREATE TABLE project_skills (
  id SERIAL PRIMARY KEY NOT NULL,
  project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
  skill_id INTEGER REFERENCES skills(id) ON DELETE CASCADE NOT NULL
);