import Head from 'next/head';
import { useState } from 'react';
import { Combobox } from '@headlessui/react';
import MyCombobox from '../components/MyCombobox';
import db from '../utils/db';

const Home = ({ projects, skills }) => {

  return (
    <div>
      <Head>
        <title>jonathan cheng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MyCombobox projects={projects} skills={skills} />
      </main>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const [projectsData, skillsData] = await Promise.all([
    db.query(`SELECT projects.*, STRING_AGG(skills.id::text, ',') AS skill_ids
      FROM projects
      INNER JOIN project_skills ON projects.id = project_skills.project_id
      INNER JOIN skills ON skills.id = project_skills.skill_id
      GROUP BY projects.id;`),
    db.query(`SELECT skills.* FROM skills;`)
  ]);
  const projects = projectsData.rows;
  const skills = skillsData.rows;

  return {
    props: { projects, skills }
  };
};