import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>jonathan cheng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className='text-6xl'>
          under construction
        </h1>
      </main>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const dev = process.env.NODE_ENV !== 'production';
  const server = dev ? 'http://localhost:3000' : '';
  const [projectsData, skillsData] = await Promise.all([
    fetch(`${server}/api/projects`),
    fetch(`${server}/api/skills`)
  ]);
  const projects = await projectsData.json();
  const skills = await skillsData.json();

  return {
    props: { projects, skills }
  };
};